// Contract ABIs - extracted from hardhat artifacts

export const hasherABI = [
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_c', type: 'uint8' },
      { name: '_salt', type: 'uint256' },
    ],
    name: 'hash',
    outputs: [{ name: '', type: 'bytes32' }],
  },
] as const

export const rpsABI = [
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_c1', type: 'uint8' },
      { name: '_c2', type: 'uint8' },
    ],
    name: 'win',
    outputs: [{ name: 'w', type: 'bool' }],
  },
  {
    constant: false,
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'j2Timeout',
    outputs: [],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'stake',
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'c2',
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'c1Hash',
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    constant: false,
    payable: true,
    stateMutability: 'payable',
    type: 'function',
    inputs: [{ name: '_c2', type: 'uint8' }],
    name: 'play',
    outputs: [],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'j2',
    outputs: [{ name: '', type: 'address' }],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'lastAction',
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    constant: false,
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_c1', type: 'uint8' },
      { name: '_salt', type: 'uint256' },
    ],
    name: 'solve',
    outputs: [],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'j1',
    outputs: [{ name: '', type: 'address' }],
  },
  {
    constant: false,
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'j1Timeout',
    outputs: [],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'TIMEOUT',
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    payable: true,
    stateMutability: 'payable',
    type: 'constructor',
    inputs: [
      { name: '_c1Hash', type: 'bytes32' },
      { name: '_j2', type: 'address' },
    ],
  },
] as const
